### ISSUE TITLE
Aditional serialization for objects (or primitive types)

### ISSUE THREAD

**Issue by adrmaster** [caelum/vraptor#325]
I have the need of (easily) add any aditional information to the serialization, something that might not be part of the model as a class attribute.

E.g: I once needed to include on the serialization the count of photos that a folder had... it could be done in a simpler way like:

      var photosCount = 30; 
      result.use(Results.xml()).from(vehicle).includeAditional(photosCount).serialize(); 

So it would include at the end of the xml or json an additional field.
I think it is also necessary for those who uses ExtJS (I don't, but I had a similar need)

**Comment by Turini** [comment]
closing here, since we already have include/exclude methods. 
```
result.use(json()).from(client).include("address").serialize();
```
ref http://www.vraptor.org/en/docs/view-and-ajax/#ajax-programmatic-version
