### ISSUE TITLE
Specify different outcomes for different formats

### ISSUE THREAD

**Issue by rafaeldff** [caelum/vraptor#36]
Make it possible for a logic method to specify different outcomes (different calls to result) for different formats. VRaptor will choose the format from the Accept header, and possibly also from request parameters.

Note: Before implementing, read [this](http://bitworking.org/news/134/Content-Negotiation-Considered-Harmful-Again) and [this](http://bitworking.org/news/WebServicesAndContentNegotiation).

(Issue by Fabio Kung)

**Comment by Turini** [comment]
closing here, since we already have `result.use(Results.representation()) ` for content negotiation ;)
