### ISSUE TITLE
Vraptor Herança com IOGI

### ISSUE THREAD

**Issue by lucasperez** [caelum/vraptor#472]
Pessoal, 

Descobri um problema na hora de instanciar objetos com herança utilizando o iogi. Ao trocar pelo ognl funcionou normalmente.

Os detalhes estão no guj nesse tópico....

http://www.guj.com.br/java/285824-vraptor-heranca#1510611

Abs,
Lucas

**Comment by Turini** [comment]
closing, based on last comment on the guj thread
