### ISSUE TITLE
Erro ao instanciar um objeto do tipo List no método do Controller (spring-3.1.1)

### ISSUE THREAD

**Issue by rpraes** [caelum/vraptor#498]
Após atualizar a versão do spring para 3.1.1, não estou conseguindo mais receber um objeto do tipo List no parâmetro de um método. Ao invés de instanciar este objeto com os ids que eu passei em um form, está vindo o valor ImportStack: [ ] . Problema passou a ocorrer após migrar o spring da 3.0.5 para 3.1.1.

Obs: Estou usando o OGNL.

**Comment by Turini** [comment]
closing here, since it's not reproducible. ok? Please reopen if you're still getting this problem ;)
