### ISSUE TITLE
DateTime problems after updating from vraptor 3.5.1 to 3.5.3

### ISSUE THREAD

**Issue by danilomunoz** [caelum/vraptor#585]
I've just update my project from vraptor 3.5.1 to 3.5.3. I have the converter for joda DateTime, but now I'm receiving null in DateTime fields.

I looked at this change https://github.com/caelum/vraptor/pull/548, but I could'n solve the problem.

May someone could give some idea how to solve this?

Thanks,

**Comment by danilomunoz** [comment]
Hi, 

I think we can close this ticket. Today we are using vraptor 4 and everthing is working fine for us. And it seems there are no more issues related by other users related to this subject.

Regards,

**Comment by Turini** [comment]
Closing. Thanks @danilomunoz!
