### ISSUE TITLE
Instantiate problem when converter exists

### ISSUE THREAD

**Issue by gutomarzagao** [caelum/vraptor#594]
Suppose you have a converter for a class Foo. When you make a resquest passing some Foo's properties as http parameters, without passing a parameter for Foo itself, you get a NullPointerException.

The problem is on VRaptorTypeConverter class inside setPropertiesAfterConversions method. At the second line, "parameter" variable becomes null and at the third line you have "parameter.getValue()" causing a NullPointerException.

Another problem of the cause is when you pass only one Foo's property as parameter still without passing a parameter for Foo itself. Then your converter is called with the property's value. For instance, suppose your Foo class have a Bar property. Then you make this request:
http://www.website.com/create?foo.bar=value
This way, your converter will wrongly reveice the "value". Note that your converter is a Foo converter, not a Bar converter.

**Comment by Turini** [comment]
closing here, since the solution was posted on guj ;)
http://www.guj.com.br/java/306808-vraptor-conversor#1632536
