### ISSUE TITLE
status().badRequest(List) não retorna o status HTTP correto, no caso de requisição "text/html"

### ISSUE THREAD

**Issue by ljtfreitas** [caelum/vraptor#600]
:warning: Problema identificado na versão 3.5.3

Na interface Status existe um método para envio do status HTTP 400 (bad request), que recebe como parâmetro um List<?>. Esse método é muito útil para enviar na resposta eventuais erros de validação (há inclusive um método na interface Validator que é um shortcut para esse método de Status). 

Ocorre que, ao menos para o caso de uma requisição "text/html", esse método não está retornando o código HTTP correto, pelo seguinte motivo:

A implementação desse método possui essa linha:

https://github.com/caelum/vraptor/blob/master/vraptor-core/src/main/java/br/com/caelum/vraptor/view/DefaultStatus.java#L146

Como o "representation" da requisição, no caso, será o "html", o VRaptor tentará serializar a coleção nesse formato, e o HtmlSerialization possui a linha abaixo:

https://github.com/caelum/vraptor/blob/master/vraptor-core/src/main/java/br/com/caelum/vraptor/serialization/HTMLSerialization.java#L45

Ou seja, o result está perdendo a configuração anterior para enviar o status bad request; ao invés disso está tentando enviar o "defaultView", o que no meu caso é 404 (não existe jsp para a action, está sendo invocada via ajax).

Não corrigi pois não sei qual seria a abordagem correta para resolver esse pequeno problema. Se puderem me indicar eu faço a correção.

Obrigado.

**Comment by Turini** [comment]
@ljtfreitas testing with vraptor4's newest version it looks to be working just fine.
I'm closing here, but you can reopen if you're still facing this problem on the latest version. ok?
cheers
