### ISSUE TITLE
vraptor 3.5.4 public maven repository?

### ISSUE THREAD

**Issue by ebett** [caelum/vraptor#603]
There are any vraptor 3.5.4 public maven repository?
I'm trying this, but doesn't work.

<dependency>
		<groupId>br.com.caelum</groupId>
		<artifactId>vraptor</artifactId>
		<version>3.5.4.FINAL</version>
</dependency>
thankyou

**Comment by Turini** [comment]
closing here, since VRaptor 3.5.4 was already released.
actually, it's now on 3.5.5:
http://search.maven.org/#artifactdetails%7Cbr.com.caelum%7Cvraptor%7C3.5.5%7Cjar
thanks guys
