### ISSUE TITLE
Ognl + Thymeleaf + VRaptor

### ISSUE THREAD

**Issue by MarceloPortilho** [caelum/vraptor#624]
Class: ReflectionBasedNullHandler
Framework involved: Thymeleaf

When using a attribute with a null value from request parameter in Thymeleaf, for some motive, it's not possible to find the Evaluation object from the context object, leading to a NullpointerException in the ReflectionBasedNullHandler class. But if the attribute is not null, the method executes normally.

- ReflectionBasedNullHandler
int indexInParent = ctx.getCurrentEvaluation().getNode().getIndexInParent();

ctx.getCurrentEvaluation()   <- returns null

- HTML
<code> input type="text" th:value="${#strings.toString(param.metadado)}" </code>

param.metadado is null, so nothing should be shown on screen, instead, it makes "ctx.getCurrentEvaluation()" returns null leading to a NullPointerException

I've made a fork/commit showing how the problem was solved here at the project being constructed with VRaptor3 + Thymeleaf:

44547c529cd91186e5e208320698e1129102ef77

Best regards, 
Marcelo Portilho.

**Comment by lucascs** [comment]
Can you open a pull request with this fix, please?

**Comment by MarceloPortilho** [comment]
Done. I think it's there. Thanks for the fast anwser.

**Comment by MarceloPortilho** [comment]
Hi, I don't want to be to daring, but I'd like to know when a next bug fix version could be released. Here at the organization I work, the architect team doesn't allow customized dependencies to be used on projects and the bug fix on this issue is located only in a custom build inside our artifactory server.

**Comment by Turini** [comment]
@marceloemanoel I've just added an comment in your PR (please let me know 
when it's done, so I can merge your changes). After that, I'll check with @lucascs 
if there is something pending and perform a new release including your fix. ok?

**Comment by marceloemanoel** [comment]
Hi @Turini I believe that you have mistaken me with @MarceloPortilho :smile:

**Comment by Turini** [comment]
Oops, mea culpa! Sorry @marceloemanoel, and thanks for letting us know :)

**Comment by lucascs** [comment]
There is nothing pending AFAIK =)

**Comment by MarceloPortilho** [comment]
I've finished doing the change on the version number.

**Comment by Turini** [comment]
@MarceloPortilho your PR has been merged. 
I'll arrange the details with @lucascs to release a new version asap.

**Comment by Turini** [comment]
closed via https://github.com/caelum/vraptor/pull/625

**Comment by MarceloPortilho** [comment]
Thank you very much =) I'll be waiting for the new release.

**Comment by Turini** [comment]
VRaptor `3.5.5` released, @MarceloPortilho! 
It can take a few hours to be available at maven's repository
