### ISSUE TITLE
Pegar body de uma requisição com anotação JSON

### ISSUE THREAD

**Issue by paulowolking** [caelum/vraptor#627]
Galera no Vraptor não consigo pegar o corpo da requisição no interceptor, porque antes de entrar no Interceptor, a requisição passa ao menos no cabeçalho do metodo no controller com anotação json, então o inputStream fica vazio. Como eu posso capturar o corpo de uma requisição com anotação json?

exemplo:

@Consumes(value = "application/json", options = WithoutRoot.class)
    @Post("/salva")
    public void salva(Usuario usuario) {
}

**Comment by lucascs** [comment]
O problema do inputStream é que você só pode ler uma vez, em geral.

O que vc quer fazer com o inputStream? Talvez vc precise de um servlet filter ao invés do interceptor do VRaptor, dependendo do que vc quer fazer.

**Comment by paulowolking** [comment]
Olá Lucas, estava querendo armazenar o conteúdo das requisições como uma espécie de logs apenas....
Estava mesmo pensando que uma solução seria realmente utilizar a classe Filter.
Obrigado.

**Comment by lucascs** [comment]
Cuidado que isso vai afetar bastante a performance do sistema, e vc deve tomar cuidado com informações confidenciais nos logs.

**Comment by lucascs** [comment]
Posso fechar a issue?

**Comment by paulowolking** [comment]
Pode sim Lucas, obrigado pela atenção e parabéns pelo livro ;D
